// ===================== Dünya Ülkeleri Veritabanı =====================

const countryData = {
  // Avrupa
  'AD': { name: 'Andorra', capital: 'Andorra la Vella', language: 'ES', region: 'Europe' },
  'AL': { name: 'Albania', capital: 'Tirana', language: 'US', region: 'Europe' },
  'AT': { name: 'Austria', capital: 'Vienna', language: 'DE', region: 'Europe' },
  'BA': { name: 'Bosnia and Herzegovina', capital: 'Sarajevo', language: 'US', region: 'Europe' },
  'BE': { name: 'Belgium', capital: 'Brussels', language: 'FR', region: 'Europe' },
  'BG': { name: 'Bulgaria', capital: 'Sofia', language: 'US', region: 'Europe' },
  'BY': { name: 'Belarus', capital: 'Minsk', language: 'US', region: 'Europe' },
  'CH': { name: 'Switzerland', capital: 'Bern', language: 'DE', region: 'Europe' },
  'CY': { name: 'Cyprus', capital: 'Nicosia', language: 'US', region: 'Europe' },
  'CZ': { name: 'Czech Republic', capital: 'Prague', language: 'US', region: 'Europe' },
  'DE': { name: 'Germany', capital: 'Berlin', language: 'DE', region: 'Europe' },
  'DK': { name: 'Denmark', capital: 'Copenhagen', language: 'US', region: 'Europe' },
  'EE': { name: 'Estonia', capital: 'Tallinn', language: 'US', region: 'Europe' },
  'ES': { name: 'Spain', capital: 'Madrid', language: 'ES', region: 'Europe' },
  'FI': { name: 'Finland', capital: 'Helsinki', language: 'US', region: 'Europe' },
  'FR': { name: 'France', capital: 'Paris', language: 'FR', region: 'Europe' },
  'GB': { name: 'United Kingdom', capital: 'London', language: 'US', region: 'Europe' },
  'GR': { name: 'Greece', capital: 'Athens', language: 'US', region: 'Europe' },
  'HR': { name: 'Croatia', capital: 'Zagreb', language: 'US', region: 'Europe' },
  'HU': { name: 'Hungary', capital: 'Budapest', language: 'US', region: 'Europe' },
  'IE': { name: 'Ireland', capital: 'Dublin', language: 'US', region: 'Europe' },
  'IS': { name: 'Iceland', capital: 'Reykjavik', language: 'US', region: 'Europe' },
  'IT': { name: 'Italy', capital: 'Rome', language: 'US', region: 'Europe' },
  'LI': { name: 'Liechtenstein', capital: 'Vaduz', language: 'DE', region: 'Europe' },
  'LT': { name: 'Lithuania', capital: 'Vilnius', language: 'US', region: 'Europe' },
  'LU': { name: 'Luxembourg', capital: 'Luxembourg', language: 'FR', region: 'Europe' },
  'LV': { name: 'Latvia', capital: 'Riga', language: 'US', region: 'Europe' },
  'MC': { name: 'Monaco', capital: 'Monaco', language: 'FR', region: 'Europe' },
  'MD': { name: 'Moldova', capital: 'Chisinau', language: 'US', region: 'Europe' },
  'ME': { name: 'Montenegro', capital: 'Podgorica', language: 'US', region: 'Europe' },
  'MK': { name: 'North Macedonia', capital: 'Skopje', language: 'US', region: 'Europe' },
  'MT': { name: 'Malta', capital: 'Valletta', language: 'US', region: 'Europe' },
  'NL': { name: 'Netherlands', capital: 'Amsterdam', language: 'US', region: 'Europe' },
  'NO': { name: 'Norway', capital: 'Oslo', language: 'US', region: 'Europe' },
  'PL': { name: 'Poland', capital: 'Warsaw', language: 'US', region: 'Europe' },
  'PT': { name: 'Portugal', capital: 'Lisbon', language: 'ES', region: 'Europe' },
  'RO': { name: 'Romania', capital: 'Bucharest', language: 'US', region: 'Europe' },
  'RS': { name: 'Serbia', capital: 'Belgrade', language: 'US', region: 'Europe' },
  'RU': { name: 'Russia', capital: 'Moscow', language: 'US', region: 'Europe' },
  'SE': { name: 'Sweden', capital: 'Stockholm', language: 'US', region: 'Europe' },
  'SI': { name: 'Slovenia', capital: 'Ljubljana', language: 'US', region: 'Europe' },
  'SK': { name: 'Slovakia', capital: 'Bratislava', language: 'US', region: 'Europe' },
  'SM': { name: 'San Marino', capital: 'San Marino', language: 'US', region: 'Europe' },
  'TR': { name: 'Turkey', capital: 'Istanbul', language: 'TR', region: 'Europe' },
  'UA': { name: 'Ukraine', capital: 'Kiev', language: 'US', region: 'Europe' },
  'VA': { name: 'Vatican City', capital: 'Vatican City', language: 'US', region: 'Europe' },

  // Kuzey Amerika
  'CA': { name: 'Canada', capital: 'Ottawa', language: 'US', region: 'North America' },
  'MX': { name: 'Mexico', capital: 'Mexico City', language: 'ES', region: 'North America' },
  'US': { name: 'United States', capital: 'Washington D.C.', language: 'US', region: 'North America' },

  // Güney Amerika
  'AR': { name: 'Argentina', capital: 'Buenos Aires', language: 'ES', region: 'South America' },
  'BO': { name: 'Bolivia', capital: 'Sucre', language: 'ES', region: 'South America' },
  'BR': { name: 'Brazil', capital: 'Brasilia', language: 'US', region: 'South America' },
  'CL': { name: 'Chile', capital: 'Santiago', language: 'ES', region: 'South America' },
  'CO': { name: 'Colombia', capital: 'Bogota', language: 'ES', region: 'South America' },
  'EC': { name: 'Ecuador', capital: 'Quito', language: 'ES', region: 'South America' },
  'FK': { name: 'Falkland Islands', capital: 'Stanley', language: 'US', region: 'South America' },
  'GF': { name: 'French Guiana', capital: 'Cayenne', language: 'FR', region: 'South America' },
  'GY': { name: 'Guyana', capital: 'Georgetown', language: 'US', region: 'South America' },
  'PE': { name: 'Peru', capital: 'Lima', language: 'ES', region: 'South America' },
  'PY': { name: 'Paraguay', capital: 'Asuncion', language: 'ES', region: 'South America' },
  'SR': { name: 'Suriname', capital: 'Paramaribo', language: 'US', region: 'South America' },
  'UY': { name: 'Uruguay', capital: 'Montevideo', language: 'ES', region: 'South America' },
  'VE': { name: 'Venezuela', capital: 'Caracas', language: 'ES', region: 'South America' },

  // Asya
  'AF': { name: 'Afghanistan', capital: 'Kabul', language: 'US', region: 'Asia' },
  'AM': { name: 'Armenia', capital: 'Yerevan', language: 'US', region: 'Asia' },
  'AZ': { name: 'Azerbaijan', capital: 'Baku', language: 'US', region: 'Asia' },
  'BD': { name: 'Bangladesh', capital: 'Dhaka', language: 'US', region: 'Asia' },
  'BH': { name: 'Bahrain', capital: 'Manama', language: 'US', region: 'Asia' },
  'BN': { name: 'Brunei', capital: 'Bandar Seri Begawan', language: 'US', region: 'Asia' },
  'BT': { name: 'Bhutan', capital: 'Thimphu', language: 'US', region: 'Asia' },
  'CC': { name: 'Cocos Islands', capital: 'West Island', language: 'US', region: 'Asia' },
  'CN': { name: 'China', capital: 'Beijing', language: 'CN', region: 'Asia' },
  'CX': { name: 'Christmas Island', capital: 'Flying Fish Cove', language: 'US', region: 'Asia' },
  'GE': { name: 'Georgia', capital: 'Tbilisi', language: 'US', region: 'Asia' },
  'HK': { name: 'Hong Kong', capital: 'Hong Kong', language: 'CN', region: 'Asia' },
  'ID': { name: 'Indonesia', capital: 'Jakarta', language: 'US', region: 'Asia' },
  'IL': { name: 'Israel', capital: 'Jerusalem', language: 'US', region: 'Asia' },
  'IN': { name: 'India', capital: 'New Delhi', language: 'US', region: 'Asia' },
  'IO': { name: 'British Indian Ocean Territory', capital: 'Diego Garcia', language: 'US', region: 'Asia' },
  'IQ': { name: 'Iraq', capital: 'Baghdad', language: 'US', region: 'Asia' },
  'IR': { name: 'Iran', capital: 'Tehran', language: 'US', region: 'Asia' },
  'JO': { name: 'Jordan', capital: 'Amman', language: 'US', region: 'Asia' },
  'JP': { name: 'Japan', capital: 'Tokyo', language: 'JP', region: 'Asia' },
  'KG': { name: 'Kyrgyzstan', capital: 'Bishkek', language: 'US', region: 'Asia' },
  'KH': { name: 'Cambodia', capital: 'Phnom Penh', language: 'US', region: 'Asia' },
  'KP': { name: 'North Korea', capital: 'Pyongyang', language: 'KR', region: 'Asia' },
  'KR': { name: 'South Korea', capital: 'Seoul', language: 'KR', region: 'Asia' },
  'KW': { name: 'Kuwait', capital: 'Kuwait City', language: 'US', region: 'Asia' },
  'KZ': { name: 'Kazakhstan', capital: 'Nur-Sultan', language: 'US', region: 'Asia' },
  'LA': { name: 'Laos', capital: 'Vientiane', language: 'US', region: 'Asia' },
  'LB': { name: 'Lebanon', capital: 'Beirut', language: 'US', region: 'Asia' },
  'LK': { name: 'Sri Lanka', capital: 'Colombo', language: 'US', region: 'Asia' },
  'MM': { name: 'Myanmar', capital: 'Naypyidaw', language: 'US', region: 'Asia' },
  'MN': { name: 'Mongolia', capital: 'Ulaanbaatar', language: 'US', region: 'Asia' },
  'MO': { name: 'Macau', capital: 'Macau', language: 'CN', region: 'Asia' },
  'MV': { name: 'Maldives', capital: 'Male', language: 'US', region: 'Asia' },
  'MY': { name: 'Malaysia', capital: 'Kuala Lumpur', language: 'US', region: 'Asia' },
  'NP': { name: 'Nepal', capital: 'Kathmandu', language: 'US', region: 'Asia' },
  'OM': { name: 'Oman', capital: 'Muscat', language: 'US', region: 'Asia' },
  'PH': { name: 'Philippines', capital: 'Manila', language: 'US', region: 'Asia' },
  'PK': { name: 'Pakistan', capital: 'Islamabad', language: 'US', region: 'Asia' },
  'PS': { name: 'Palestine', capital: 'Ramallah', language: 'US', region: 'Asia' },
  'QA': { name: 'Qatar', capital: 'Doha', language: 'US', region: 'Asia' },
  'SA': { name: 'Saudi Arabia', capital: 'Riyadh', language: 'US', region: 'Asia' },
  'SG': { name: 'Singapore', capital: 'Singapore', language: 'US', region: 'Asia' },
  'SY': { name: 'Syria', capital: 'Damascus', language: 'US', region: 'Asia' },
  'TH': { name: 'Thailand', capital: 'Bangkok', language: 'US', region: 'Asia' },
  'TJ': { name: 'Tajikistan', capital: 'Dushanbe', language: 'US', region: 'Asia' },
  'TL': { name: 'East Timor', capital: 'Dili', language: 'US', region: 'Asia' },
  'TM': { name: 'Turkmenistan', capital: 'Ashgabat', language: 'US', region: 'Asia' },
  'TW': { name: 'Taiwan', capital: 'Taipei', language: 'CN', region: 'Asia' },
  'UZ': { name: 'Uzbekistan', capital: 'Tashkent', language: 'US', region: 'Asia' },
  'VN': { name: 'Vietnam', capital: 'Hanoi', language: 'US', region: 'Asia' },
  'YE': { name: 'Yemen', capital: 'Sanaa', language: 'US', region: 'Asia' },

  // Afrika
  'AO': { name: 'Angola', capital: 'Luanda', language: 'US', region: 'Africa' },
  'BF': { name: 'Burkina Faso', capital: 'Ouagadougou', language: 'FR', region: 'Africa' },
  'BI': { name: 'Burundi', capital: 'Gitega', language: 'FR', region: 'Africa' },
  'BJ': { name: 'Benin', capital: 'Porto-Novo', language: 'FR', region: 'Africa' },
  'BW': { name: 'Botswana', capital: 'Gaborone', language: 'US', region: 'Africa' },
  'CD': { name: 'Democratic Republic of the Congo', capital: 'Kinshasa', language: 'FR', region: 'Africa' },
  'CF': { name: 'Central African Republic', capital: 'Bangui', language: 'FR', region: 'Africa' },
  'CG': { name: 'Republic of the Congo', capital: 'Brazzaville', language: 'FR', region: 'Africa' },
  'CI': { name: 'Ivory Coast', capital: 'Yamoussoukro', language: 'FR', region: 'Africa' },
  'CM': { name: 'Cameroon', capital: 'Yaounde', language: 'FR', region: 'Africa' },
  'CV': { name: 'Cape Verde', capital: 'Praia', language: 'US', region: 'Africa' },
  'DJ': { name: 'Djibouti', capital: 'Djibouti', language: 'FR', region: 'Africa' },
  'DZ': { name: 'Algeria', capital: 'Algiers', language: 'FR', region: 'Africa' },
  'EG': { name: 'Egypt', capital: 'Cairo', language: 'US', region: 'Africa' },
  'EH': { name: 'Western Sahara', capital: 'El Aaiun', language: 'US', region: 'Africa' },
  'ER': { name: 'Eritrea', capital: 'Asmara', language: 'US', region: 'Africa' },
  'ET': { name: 'Ethiopia', capital: 'Addis Ababa', language: 'US', region: 'Africa' },
  'GA': { name: 'Gabon', capital: 'Libreville', language: 'FR', region: 'Africa' },
  'GH': { name: 'Ghana', capital: 'Accra', language: 'US', region: 'Africa' },
  'GM': { name: 'Gambia', capital: 'Banjul', language: 'US', region: 'Africa' },
  'GN': { name: 'Guinea', capital: 'Conakry', language: 'FR', region: 'Africa' },
  'GQ': { name: 'Equatorial Guinea', capital: 'Malabo', language: 'ES', region: 'Africa' },
  'GW': { name: 'Guinea-Bissau', capital: 'Bissau', language: 'US', region: 'Africa' },
  'KE': { name: 'Kenya', capital: 'Nairobi', language: 'US', region: 'Africa' },
  'KM': { name: 'Comoros', capital: 'Moroni', language: 'FR', region: 'Africa' },
  'LR': { name: 'Liberia', capital: 'Monrovia', language: 'US', region: 'Africa' },
  'LS': { name: 'Lesotho', capital: 'Maseru', language: 'US', region: 'Africa' },
  'LY': { name: 'Libya', capital: 'Tripoli', language: 'US', region: 'Africa' },
  'MA': { name: 'Morocco', capital: 'Rabat', language: 'FR', region: 'Africa' },
  'MG': { name: 'Madagascar', capital: 'Antananarivo', language: 'FR', region: 'Africa' },
  'ML': { name: 'Mali', capital: 'Bamako', language: 'FR', region: 'Africa' },
  'MR': { name: 'Mauritania', capital: 'Nouakchott', language: 'FR', region: 'Africa' },
  'MU': { name: 'Mauritius', capital: 'Port Louis', language: 'US', region: 'Africa' },
  'MW': { name: 'Malawi', capital: 'Lilongwe', language: 'US', region: 'Africa' },
  'MZ': { name: 'Mozambique', capital: 'Maputo', language: 'US', region: 'Africa' },
  'NA': { name: 'Namibia', capital: 'Windhoek', language: 'US', region: 'Africa' },
  'NE': { name: 'Niger', capital: 'Niamey', language: 'FR', region: 'Africa' },
  'NG': { name: 'Nigeria', capital: 'Abuja', language: 'US', region: 'Africa' },
  'RW': { name: 'Rwanda', capital: 'Kigali', language: 'FR', region: 'Africa' },
  'SC': { name: 'Seychelles', capital: 'Victoria', language: 'US', region: 'Africa' },
  'SD': { name: 'Sudan', capital: 'Khartoum', language: 'US', region: 'Africa' },
  'SL': { name: 'Sierra Leone', capital: 'Freetown', language: 'US', region: 'Africa' },
  'SN': { name: 'Senegal', capital: 'Dakar', language: 'FR', region: 'Africa' },
  'SO': { name: 'Somalia', capital: 'Mogadishu', language: 'US', region: 'Africa' },
  'SS': { name: 'South Sudan', capital: 'Juba', language: 'US', region: 'Africa' },
  'ST': { name: 'Sao Tome and Principe', capital: 'Sao Tome', language: 'US', region: 'Africa' },
  'SZ': { name: 'Eswatini', capital: 'Mbabane', language: 'US', region: 'Africa' },
  'TD': { name: 'Chad', capital: 'N\'Djamena', language: 'FR', region: 'Africa' },
  'TG': { name: 'Togo', capital: 'Lome', language: 'FR', region: 'Africa' },
  'TN': { name: 'Tunisia', capital: 'Tunis', language: 'FR', region: 'Africa' },
  'TZ': { name: 'Tanzania', capital: 'Dodoma', language: 'US', region: 'Africa' },
  'UG': { name: 'Uganda', capital: 'Kampala', language: 'US', region: 'Africa' },
  'ZA': { name: 'South Africa', capital: 'Cape Town', language: 'US', region: 'Africa' },
  'ZM': { name: 'Zambia', capital: 'Lusaka', language: 'US', region: 'Africa' },
  'ZW': { name: 'Zimbabwe', capital: 'Harare', language: 'US', region: 'Africa' },

  // Okyanusya
  'AS': { name: 'American Samoa', capital: 'Pago Pago', language: 'US', region: 'Oceania' },
  'AU': { name: 'Australia', capital: 'Canberra', language: 'US', region: 'Oceania' },
  'CK': { name: 'Cook Islands', capital: 'Avarua', language: 'US', region: 'Oceania' },
  'FJ': { name: 'Fiji', capital: 'Suva', language: 'US', region: 'Oceania' },
  'FM': { name: 'Micronesia', capital: 'Palikir', language: 'US', region: 'Oceania' },
  'GU': { name: 'Guam', capital: 'Hagatna', language: 'US', region: 'Oceania' },
  'KI': { name: 'Kiribati', capital: 'Tarawa', language: 'US', region: 'Oceania' },
  'MH': { name: 'Marshall Islands', capital: 'Majuro', language: 'US', region: 'Oceania' },
  'MP': { name: 'Northern Mariana Islands', capital: 'Saipan', language: 'US', region: 'Oceania' },
  'NC': { name: 'New Caledonia', capital: 'Noumea', language: 'FR', region: 'Oceania' },
  'NF': { name: 'Norfolk Island', capital: 'Kingston', language: 'US', region: 'Oceania' },
  'NR': { name: 'Nauru', capital: 'Yaren', language: 'US', region: 'Oceania' },
  'NU': { name: 'Niue', capital: 'Alofi', language: 'US', region: 'Oceania' },
  'NZ': { name: 'New Zealand', capital: 'Wellington', language: 'US', region: 'Oceania' },
  'PF': { name: 'French Polynesia', capital: 'Papeete', language: 'FR', region: 'Oceania' },
  'PG': { name: 'Papua New Guinea', capital: 'Port Moresby', language: 'US', region: 'Oceania' },
  'PN': { name: 'Pitcairn Islands', capital: 'Adamstown', language: 'US', region: 'Oceania' },
  'PW': { name: 'Palau', capital: 'Ngerulmud', language: 'US', region: 'Oceania' },
  'SB': { name: 'Solomon Islands', capital: 'Honiara', language: 'US', region: 'Oceania' },
  'TK': { name: 'Tokelau', capital: 'Nukunonu', language: 'US', region: 'Oceania' },
  'TO': { name: 'Tonga', capital: 'Nuku\'alofa', language: 'US', region: 'Oceania' },
  'TV': { name: 'Tuvalu', capital: 'Funafuti', language: 'US', region: 'Oceania' },
  'VU': { name: 'Vanuatu', capital: 'Port Vila', language: 'FR', region: 'Oceania' },
  'WF': { name: 'Wallis and Futuna', capital: 'Mata-Utu', language: 'FR', region: 'Oceania' },
  'WS': { name: 'Samoa', capital: 'Apia', language: 'US', region: 'Oceania' }
};

// Ülke kodundan ülke bilgilerini al
function getCountryInfo(countryCode) {
  return countryData[countryCode] || {
    name: 'Unknown',
    capital: 'Unknown',
    language: 'US',
    region: 'Unknown'
  };
}

// Tüm ülkeleri bölgeye göre grupla
function getCountriesByRegion(region) {
  return Object.entries(countryData)
    .filter(([code, info]) => info.region === region)
    .map(([code, info]) => ({ code, ...info }));
}

// Dil koduna göre ülkeleri filtrele
function getCountriesByLanguage(language) {
  return Object.entries(countryData)
    .filter(([code, info]) => info.language === language)
    .map(([code, info]) => ({ code, ...info }));
}

// Global olarak erişilebilir yap
window.countryData = countryData;
window.getCountryInfo = getCountryInfo;
window.getCountriesByRegion = getCountriesByRegion;
window.getCountriesByLanguage = getCountriesByLanguage;
